plt.figure()
plt.xticks((), ())
plt.yticks((), ())
ax.text(0.2, 0.2, 'Email a notebook\n(best-case scenario)')
ax.text(0.2, 0.8, 'Email a notebook\n(common scenario)')
ax.text(0.8, 0.2, 'Binder')
plt.xlabel('Sender effort or expertise')
plt.ylabel('Recipient effort or expertise')
ax.text(0.1, 0.1, 'Share Link', color='xkcd:blue')
ax.text(0.6, 0.2, 'UI for defining\na REES?', color='xkcd:blue')
